\mainmatter
\pagestyle{main}

# 这是什么 {#chap:intro}

这是上海交通大学(非官方)学位论文 Bookdown 模板，当前处于草稿期 。

据最新[2018-06-08]的[上海交通大学学位论文Latex模板](https://github.com/sjtug/SJTUThesis)， 参考[谢益辉Bookdown中文模板](https://github.com/yihui/bookdown-chinese)改写而成 \cite{xie2015}。其中图片，代码等问题尚未解决。但是能够编译成书了\cite{IEEE-1363}。

## 模板使用

### 准备工作

本模板使用 bookdown 实现了由 R Markdown （Bookdown） -> LaTeX -> PDF 的一系列转换，其中用到的依赖有：

- bookdown
- pandoc
- Tex

需要安装这些软件，才可以使用。

#### Linux 下使用

下面以深度操作系统15.5版本为例说明。安装过程中，请确保当前 `rstudio` 的版本高于 1.0.0, texlive 为2015年及之后的版本。

```bash
$ sudo apt-get install r-base r-base-dev \
rstudio texlive-full pandoc
```

如果不能满足，请参考相关软件官网，下载最新版本。

#### Windows 下使用

略

#### 苹果操作系统下使用

略

### 模板选项

sjtuthesis-rmd 提供了一些常用选项，可以组合使用，在 *./index.Rmd* 文件中配置。具体配置方法，见后文。
这些选项包括：

- 学位类型：bachelor(学位)、master(硕士)、doctor(博士)，是必选项。
- 中文字体：fandol(Fandol 开源字体)、windows(Windows 系统下的中文字体)、mac(macOS 系统下的华文字体)、ubuntu(Ubuntu 系统下的文泉驿和文鼎字体)、adobe(Adobe 公司的中文字体)、founder(方正公司的中文字体)，默认根据操作系统自动配置。
- 英文模版：使用english选项启用英文模版。
- 盲审选项：使用review选项后，论文作者、学号、导师姓名、致谢、发表论文和参与项目将被隐去。

### 编译模板

模板默认使用GNUMake构建，

```bash
$ make
```

换到原始方式，

\begin{lstlisting}[basicstyle=\small\ttfamily, caption={编译模板}, numbers=none]
make
\end{lstlisting}

在已经安装 RStudio 的前提下，也可手动编译。打开 RStudio 软件，在弹出的界面，左上角点击 File->Open Project，选中 *./SJTUThesis-Rmd.Rproj* 文件打开，点击右上角靠下的一栏，有个 `Build` 格，会出现 `Build Book` 等按钮。
点击 `Build Book` 就会生成 PDF 书籍了，位于 *./\_book/sjtu-thesis-rmd.pdf* 。

### 文件布局

使用 `tree` 命令所得。
\begin{lstlisting}[basicstyle=\small\ttfamily,caption={模板文件布局},label=layout,numbers=none]
├── bib
│   └── thesis.bib
├── _book
│   ├── sjtu-thesis-rmd.pdf
│   └── sjtu-thesis-rmd.tex
├── _bookdown_files
├── _bookdown.yml
├── figure
│   ├── example
│   │   ├── flow_chart.tex
│   │   ├── sjtulogo.eps
│   │   ├── sjtulogo.jpg
│   │   └── sjtulogo.png
│   ├── sjtubadge.pdf
│   ├── sjtubanner.pdf
│   └── sjtulogo.pdf
├── handed_pdf
│   ├── authorization.pdf
│   └── original.pdf
├── index.Rmd
├── tex
│   ├── ack.tex
│   ├── content.tex
│   ├── end_english_abstract.tex
│   ├── patents.tex
│   ├── projectsreview.tex
│   ├── projects.tex
│   ├── pubreview.tex
│   ├── pub.tex
│   └── template.tex
├── Makefile
├── _output.yml
├── README.md
├── _render.R
├── rmd
│   ├── 000-abstract.Rmd
│   ├── 001-symbol.Rmd
│   ├── 003-author.Rmd
│   ├── 101-intro.Rmd
│   ├── 102-chapters.Rmd
│   ├── 103-latex.Rmd
│   ├── 104-rmarkdown.Rmd
│   ├── 105-example.Rmd
│   ├── 601-appendix-bookdown.Rmd
│   ├── 602-appendix-tale.Rmd
│   ├── 603-appendix-history.Rmd
│   └── 604-appendix-r-diagram.Rmd
├── sjtuthesis.cfg
├── sjtuthesis.cls
└── SJTUThesis-Rmd.Rproj

\end{lstlisting}

### 主要文件介绍

#### LaTeX 模板文件

格式控制文件控制着论文的表现形式，包括 *./sjtuthesis.cfg* 和 *./sjtuthesis.cls*。
其中，“cls”控制论文主体格式，“cfg”为配置文件。上述文件全部来自[上海交通大学学位论文Latex模板](https://github.com/sjtug/SJTUThesis)

#### 各章源文件

主要位于 *./rmd/* 文件夹。由于现阶段部分功能实现不全，暂且把部分内容以 latex 形式存放在 *./tex/* 文件夹下。

#### 配置文件

主要有

- _bookdown.yml
- _output.yml