# 愚公移山 {#yugong}

<p style="text-align: right;">
———— 先秦 列御寇 
</p>

太行、 王屋二山， 方七百里， 高万仞， 本在冀州之南， 河阳之北。

北山愚公者， 年且九十， 面山而居。 惩山北之塞， 出入之迂也， 聚室而谋曰： “吾与汝毕力平险， 指通豫南， 达于汉阴， 可乎？” 杂然相许。 其妻献疑曰： “以君之力， 曾不能损魁父之丘， 如太行、 王屋何？ 且焉置土石？” 杂曰： “投诸渤海之尾， 隐土之北。” 遂率子孙荷担者三夫， 叩石垦壤， 箕畚运于渤海之尾。 邻人京城氏之孀妻有遗男， 始龀， 跳往助之。 寒暑易节， 始一返焉。

河曲智叟笑而止之曰： “甚矣， 汝之不惠！ 以残年余力， 曾不能毁山之一毛， 其如土石何？” 北山愚公长息曰： “汝心之固， 固不可彻， 曾不若孀妻弱子。 虽我之死， 有子存焉； 子又生孙， 孙又生子； 子又有子， 子又有孙； 子子孙孙无穷匮也， 而山不加增， 何苦而不平？” 河曲智叟亡以应。

操蛇之神闻之， 惧其不已也， 告之于帝。 帝感其诚， 命夸娥氏二子负二山， 一厝朔东， 一厝雍南。 自此， 冀之南， 汉之阴， 无陇断焉。 

选择二维情况，有如下的偏振矢量：
\begin{subequations}
  \begin{eqnarray}
    {\bf E}&=&E_z(r,\theta)\hat{\bf z} \\
    {\bf H}&=&H_r(r,\theta))\hat{ \bf r}+H_\theta(r,\theta)\hat{\bm
      \theta}
  \end{eqnarray}
\end{subequations}
对上式求旋度：
\begin{subequations}
  \begin{eqnarray}
    \nabla\times{\bf E}&=&\frac{1}{r}\frac{\partial E_z}{\partial\theta}{\hat{\bf r}}-\frac{\partial E_z}{\partial r}{\hat{\bm\theta}}\\
    \nabla\times{\bf H}&=&\left[\frac{1}{r}\frac{\partial}{\partial
        r}(rH_\theta)-\frac{1}{r}\frac{\partial
        H_r}{\partial\theta}\right]{\hat{\bf z}}
  \end{eqnarray}
\end{subequations}
因为在柱坐标系下，$\overline{\overline\mu}$是对角的，所以Maxwell方程组中电场$\bf E$的旋度：
\begin{subequations}
  \begin{eqnarray}
    &&\nabla\times{\bf E}=\mathbf{i}\omega{\bf B} \\
    &&\frac{1}{r}\frac{\partial E_z}{\partial\theta}{\hat{\bf
        r}}-\frac{\partial E_z}{\partial
      r}{\hat{\bm\theta}}=\mathbf{i}\omega\mu_rH_r{\hat{\bf r}}+\mathbf{i}\omega\mu_\theta
    H_\theta{\hat{\bm\theta}}
  \end{eqnarray}
\end{subequations}
所以$\bf H$的各个分量可以写为：
\begin{subequations}
  \begin{eqnarray}
    H_r=\frac{1}{\mathbf{i}\omega\mu_r}\frac{1}{r}\frac{\partial
      E_z}{\partial\theta } \\
    H_\theta=-\frac{1}{\mathbf{i}\omega\mu_\theta}\frac{\partial E_z}{\partial r}
  \end{eqnarray}
\end{subequations}
同样地，在柱坐标系下，$\overline{\overline\epsilon}$是对角的，所以Maxwell方程组中磁场$\bf H$的旋度：
\begin{subequations}
  \begin{eqnarray}
    &&\nabla\times{\bf H}=-\mathbf{i}\omega{\bf D}\\
    &&\left[\frac{1}{r}\frac{\partial}{\partial
        r}(rH_\theta)-\frac{1}{r}\frac{\partial
        H_r}{\partial\theta}\right]{\hat{\bf
        z}}=-\mathbf{i}\omega{\overline{\overline\epsilon}}{\bf
      E}=-\mathbf{i}\omega\epsilon_zE_z{\hat{\bf z}} \\
    &&\frac{1}{r}\frac{\partial}{\partial
      r}(rH_\theta)-\frac{1}{r}\frac{\partial
      H_r}{\partial\theta}=-\mathbf{i}\omega\epsilon_zE_z
  \end{eqnarray}
\end{subequations}
由此我们可以得到关于$E_z$的波函数方程：
\begin{eqnarray}
  \frac{1}{\mu_\theta\epsilon_z}\frac{1}{r}\frac{\partial}{\partial r}
  \left(r\frac{\partial E_z}{\partial r}\right)+
  \frac{1}{\mu_r\epsilon_z}\frac{1}{r^2}\frac{\partial^2E_z}{\partial\theta^2}
  +\omega^2 E_z=0
\end{eqnarray}
