```{r setup, include=FALSE}

# 为了让日期显示为英文
locale = Sys.setlocale(category = "LC_TIME", locale = 'en_US.UTF-8')
localSystem = R.Version()$system

options(
  htmltools.dir.version = FALSE, formatR.indent = 2, width = 55, digits = 4
)

if (system('phantomjs --version') != 0)
  webshot::install_phantomjs()

# 生成依赖包
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'htmlwidgets', 'webshot', 'DT',
  'miniUI', 'tufte', 'servr', 'citr', 'rticles'
), 'bib/packages.bib')

# 支持图片标题双语言，为了排版优化，强制加入 \centering
# https://github.com/yihui/knitr/issues/1554
library(knitr)
knit_hooks$set(plot = function(x, options) {
  if(!is.null(options$bicap)){
    paste("\\begin{figure}[!htp]",
        "\n\\centering",
        hook_plot_tex(x, options), 
        "\n\\bicaption{", options$bicap[1], "}{",options$bicap[2],"}", 
        "\n\\end{figure}", sep = "")
  }
  else{
    hook_plot_tex(x, options)
  }
})

```
--- 
title: "上海交通大学论文 Rmd bookdown 模板"
author: "某 \\quad 某"
documentclass: sjtuthesis
classoption: [doctor, openright, twoside]
studentnumber: B1103492
school: "上海交通大学"
advisor: "深度操作系统"
major: "通信与信息系统"
defenddate: "`r format(Sys.Date(),format='%Y年%m月%d日')`"
date: "`r format(Sys.Date(),format='%Y年%m月%d日')`"
keywords: "上海交大\\quad 饮水思源\\quad 爱国荣校"
englishauthor: "Mou Mou"
englishadvisor: "Deepin"
englishinstitute: "Deepin OS"
englishdate: "`r format(Sys.Date(),format='%b. %d, %Y')`"
englishtitle: "SJTU Bookdown Template"
englishmajor: "Comminucation and Information Tech"
englishkeywords: "SJTU, XeTeX/LaTeX template, Bookdown, Rmarkdown"
bibliography: [bib/thesis.bib, bib/packages.bib]
biblio-style: apalike
link-citations: yes
colorlinks: yes
lot: yes
lof: yes
href2footnote: yes
github-repo: bubifengyun/SJTUThesis-Rmd
---


